"""relate users to book foreignkey"

Revision ID: 276cbad40d1c
Revises: c8d20ec0972b
Create Date: 2026-07-30 18:25:23.967394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '276cbad40d1c'
down_revision: Union[str, Sequence[str], None] = 'c8d20ec0972b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BOOKS', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'BOOKS', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'BOOKS', type_='foreignkey')
    op.drop_column('BOOKS', 'user_uid')
    # ### end Alembic commands ###
